module.exports = {
  VALID_EXTENSIONS: [".js", ".jsx", ".ts", ".tsx"],
  IGNORED_FOLDERS: ["node_modules", ".git", ".next", "dist", "build"],
  IGNORED_FILES: [
    "package.json",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "eslint.config.cjs",
    ".eslintrc.js",
    ".eslintrc.json",
    ".prettierrc",
    ".prettierrc.js",
    ".prettierrc.json",
    "tailwindcss.config.js",
    "tsconfig.json",
    "next.config.json",
  ],
  DEFAULT_LINT_MODE: "parallel",
  MAX_PARALLEL: 5,
};
